FROM ubuntu:20.04
MAINTAINER Alojzij Blatnik

ARG ARG_UID
ARG ARG_GID
ARG TIMEZONE

ENV DEBIAN_FRONTEND noninteractive

RUN \
    echo "user:x:${ARG_UID}:${ARG_GID}:User,,,:/home/user:/bin/bash" >> /etc/passwd && \
    echo "user:x:${ARG_UID}:" >> /etc/group && \
    mkdir /home/user && \
    chown user:user /home/user && \
    \
    apt-get update && \
    apt-get install -y \
        fonts-roboto \
        fonts-symbola \
        fonts-liberation \
        firefox \
        ubuntu-restricted-extras \
        pulseaudio \
        wget \
        tzdata \
        hicolor-icon-theme \
        libcanberra-gtk-module \
        libexif-dev \
        libgl1-mesa-dri \
        libgl1-mesa-glx \
        libpango1.0-0 \
        libv4l-0 \
        && \
    \
    echo "${TIMEZONE}" > /etc/timezone && \
    dpkg-reconfigure -f noninteractive tzdata && \
    \
    rm /usr/share/fonts/truetype/roboto/unhinted/RobotoCondensed-* && \
    rm /usr/share/fonts/truetype/liberation/LiberationSansNarrow-*

USER user

VOLUME ["/home/user"]
CMD /usr/bin/firefox

